# Q3: Build prediction model for churn out rate
Attrition_Data<-read.csv("D:\\Dataset-Linear Regression\\emp_data.csv")
View(Attrition_Data)
summary(Attrition_Data)
Salary_hike<-Attrition_Data$Salary_hike
Churn_out_Rate<-Attrition_Data$Churn_out_rate
var(Salary_hike)
sd(Salary_hike)
var(Churn_out_Rate)
sd(Churn_out_Rate)
install.packages("moments")
library(moments)
skewness(Salary_hike)
skewness(Churn_out_Rate)
kurtosis(Salary_hike)
kurtosis(Churn_out_Rate)
install.packages("lattice")
library(lattice)
dotplot(Salary_hike)
dotplot(Churn_out_Rate)
boxplot(Salary_hike)
boxplot(Churn_out_Rate)
hist(Salary_hike)
hist(Churn_out_Rate)
plot(Salary_hike,Churn_out_Rate)
cor(Salary_hike,Churn_out_Rate)
model<-lm(Churn_out_Rate~Salary_hike,data=Attrition_Data)
summary(model)
plot(model)
model1<-lm(Churn_out_Rate~log(Salary_hike),data=Attrition_Data)
summary(model1)
model2<-lm((log(Churn_out_Rate)~Salary_hike),data=Attrition_Data)
summary(model2)
model3<-lm((Churn_out_Rate~Salary_hike+I(Salary_hike^2)),data=Attrition_Data)
summary(model3)
pred<-predict(model3,interval="predict")
View(pred)
pred1<-data.frame(pred)
cor(Salary_hike,pred1$fit)
# R-Square value is 83% which is a very good model
# Checking of model at salary hike of 1500
